### ISSUE TITLE
Attempts to divide by zero when using axe without unbreaking, and fails to break blocks

### ISSUE THREAD

**Issue by elliottbw** [SourceWriters/SmoothTimber#1]
When "timbering" with an axe that lacks the unbreaking enchantment, the plugin attempts to divide by zero when removing durability from that axe, and doesn't break any blocks. The initial block is replaced.

Here is the stack trace:

```
[SmoothTimber] Task #180171 for SmoothTimber v1.5.6 generated an exception
java.lang.ArithmeticException: / by zero
        at com.syntaxphoenix.spigot.smoothtimber.version.changer.v1_13xChanger.removeDurabilityFromItem(v1_13xChanger.java:30) ~[?:?]
        at com.syntaxphoenix.spigot.smoothtimber.listener.BlockBreakListener$1$1.run(BlockBreakListener.java:68) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-143]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-143]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Lauriichen** [comment]
okay so I fixed that in v1.6.0
Thanks for your report :D
