### ISSUE TITLE
[COMPAT] Add compatibility for JobsReborn newest version

### ISSUE THREAD

**Issue by draand28** [SourceWriters/SmoothTimber#12]
**Describe the bug**
Just installed SmoothTimber 1.17.1 on Paper 1.17 build 42 and whenever I try to cut down a tree, the tree cuts just fine, but I'm getting the error mentioned below.

**To Reproduce**

1. Use Java 16, Paper 1.17 Build 42 and Smooth Timber 1.17.1
2. Try to cut a tree
3. See error

**Expected behavior**
No error in console

**Media**
`[19:47:59 ERROR]: Could not pass event AsyncPlayerTreeFallEvent to SmoothTimber v1.17.1
java.lang.NoSuchMethodError: 'java.lang.String com.gamingmesh.jobs.container.Job.getJobKeyName()'
        at com.syntaxphoenix.spigot.smoothtimber.compatibility.jobsreborn.JobsRebornFallListener.onFallEvent(JobsRebornFallListener.java:31) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor573.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
        at com.syntaxphoenix.spigot.smoothtimber.SmoothTimber.triggerFallEvent(SmoothTimber.java:70) ~[?:?]
        at com.syntaxphoenix.spigot.smoothtimber.listener.BlockBreakListener$1$1.lambda$run$0(BlockBreakListener.java:115) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
`

**Server:**

 - Software: [e.g. Spigot] Paper
 - Server Version: [e.g. 1.16.5]  1.17 build 42
 - Plugin Version: [e.g. 1.0.0]  1.17.1
 - Java Version: [e.g. 1.8.0u281 / 1.8.0_281 / 8] 16.0.1+9-24

**Comment by Lauriichan** [comment]
This has to do with JobsReborn, please disable jobs reborn support for now

**Comment by Lauriichan** [comment]
added with f0f381ccb6c6f5ba8bd4dfd86decc9789879f926
