### ISSUE TITLE
[BUG] Not able to chop custom generated jungle wood

### ISSUE THREAD

**Issue by grimolo** [SourceWriters/SmoothTimber#18]
**Describe the bug**
When you chop jungle wood (not the log, the wood with tree textures on every side) with an axe it doesn't break the block. Nothing drops and the animation just ends, while an error message is created in the console .

**To Reproduce**

1. Go to a tree structure with jungle wood (not the logs and not the planks)
2. Try to chop some wood off the tree with an axe by holding your left mouse button
3. Look at the console

**Expected behavior**
The chopped block should be dropped, just like the other variants (oak wood). 

**Media**
 Screenshot of the error message: https://imgur.com/a/CRsgP4u
Video of it happening in game: https://www.youtube.com/watch?v=RugUOPH_eXw

**Server:**
 - Software: [PaperMC]
 - Server Version: [1.17.1]
 - Plugin Version: [v1.17.8]
 - Java Version: [16]

**Additional context**
We do use the plugin TerraFormGenerator for these special kind of trees. But it does work with oak trees so I don't see why it shouldn't work with jungle trees.
Here is the error message:
[14:12:03 WARN]: [SmoothTimber] Plugin SmoothTimber v1.17.8 generated an exception while executing task 496
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "resolve" is null
        at com.syntaxphoenix.spigot.smoothtimber.utilities.locate.Locator.locateWood(Locator.java:85) ~[smoothtimber-legacy-1.17.8.jar:?]
        at com.syntaxphoenix.spigot.smoothtimber.listener.BlockBreakListener$1.run(BlockBreakListener.java:93) ~[smoothtimber-legacy-1.17.8.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-304]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-304]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-304]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by YellowPhoenix18** [comment]
@grimolo Can you please rename your title? That title is not clear

**Comment by grimolo** [comment]
Of course, sorry. Forgot to remove the template title. I hope it's more clear now.

**Comment by Lauriichan** [comment]
Fixed with ab96c27170f8197e6cc8aa80464f66b6a619c862
