### ISSUE TITLE
[BUG][Compatibility] GriefPrevention compatibility bug

### ISSUE THREAD

**Issue by KoenLemmen** [SourceWriters/SmoothTimber#25]
**Describe the bug**
Unfortunately I don't really know what is happening here. A player on my server is stating:
"I cannot down a tree at once that I have bonemealed."
And this is the only error I got in console.
I also don't really know for certain if this is a SmoothTimber bug but with that player reported and SmoothTimber being mentioned in the trace stack at: com.syntaxphoenix.spigot.smoothtimber.listener.BlockBreakListener, com.syntaxphoenix.spigot.smoothtimber.SmoothTimber.triggerChopEvent and com.syntaxphoenix.spigot.smoothtimber.compatibility.griefprevention.GriefPreventionChopListener.onChopEvent
I at least had to send this, please let me know if this is a GriefPrevention thing.

**To Reproduce**
Difficult to know.
Have a griefprevention claim, bone meal a tree, try and break it

**Expected behavior**
Tree falls down at once instead of block by block
No error in logs

**Log**
`java.lang.IllegalStateException: ClaimPermissionCheckEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:616) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at me.ryanhamshire.GriefPrevention.Claim.callPermissionCheck(Claim.java:493) ~[GriefPrevention.jar:?]
        at me.ryanhamshire.GriefPrevention.Claim.checkPermission(Claim.java:458) ~[GriefPrevention.jar:?]
        at me.ryanhamshire.GriefPrevention.Claim.checkPermission(Claim.java:444) ~[GriefPrevention.jar:?]
        at me.ryanhamshire.GriefPrevention.Claim.allowBreak(Claim.java:584) ~[GriefPrevention.jar:?]
        at com.syntaxphoenix.spigot.smoothtimber.compatibility.griefprevention.GriefPreventionChopListener.onChopEvent(GriefPreventionChopListener.java:37) ~[smoothtimber-legacy-1.18.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor269.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-57]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at com.syntaxphoenix.spigot.smoothtimber.SmoothTimber.triggerChopEvent(SmoothTimber.java:53) ~[smoothtimber-legacy-1.18.1.jar:?]
        at com.syntaxphoenix.spigot.smoothtimber.listener.BlockBreakListener$1.run(BlockBreakListener.java:94) ~[smoothtimber-legacy-1.18.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.jar:git-Paper-57]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.jar:git-Paper-57]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.jar:git-Paper-57]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Server:**

 - Software: Paper
 - Server Version: This server is running Paper version git-Paper-57 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 53d026e)
 - Plugin Version: 1.18.1
 - Java Version: 17

**Comment by Lauriichan** [comment]
The problem here is that SmoothTimber is checking if the blocks are in a region async which the event of GriefPrevention doesn't allow

**Comment by KoenLemmen** [comment]
Should I send this to the GriefPrevention devs? Or am I in the right place?

**Comment by Lauriichan** [comment]
Yeah you're at the right place here ^^

**Comment by KoenLemmen** [comment]
Thanks again for fixing the bug. Is this the bug players described to me about not being able to take down trees that were bonemealed in their farms or was it something different?

**Comment by PierreSchwang** [comment]
> Thanks again for fixing the bug. Is this the bug players described to me about not being able to take down trees that were bonemealed in their farms or was it something different?

Issue was an API change by GriefPrevention which resulted in an error on checking blocks and cancelled the whole tree-chopping-interaction.
