### ISSUE TITLE
[BUG] Some bug that happend

### ISSUE THREAD

**Issue by Paradox101** [SourceWriters/SmoothTimber#31]
**Describe the bug**
Receiving error messages while no one is using plugin at that moment.

> WARN01:07:24
[SmoothTimber]: Plugin SmoothTimber v1.18.3 generated an exception while executing task 2696900
Console01:07:24
java.lang.IllegalStateException: Tile is null, asynchronous access? CraftBlock{pos=BlockPosition{x=-786, y=98, z=-1511},type=BEE_NEST,data=Block{minecraft:bee_nest}[facing=south,honey_level=0],fluid=net.minecraft.world.level.material.FluidTypeEmpty@650c1d6e}
at com.google.common.base.Preconditions.checkState(Preconditions.java:590) ~[guava-31.0.1-jre.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:89) ~[paper-1.18.1.jar:git-Paper-132]
at org.bukkit.craftbukkit.v1_18_R1.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:75) ~[paper-1.18.1.jar:git-Paper-132]
at org.bukkit.craftbukkit.v1_18_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:250) ~[paper-1.18.1.jar:git-Paper-132]
at org.bukkit.craftbukkit.v1_18_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:213) ~[paper-1.18.1.jar:git-Paper-132]
at org.bukkit.craftbukkit.v1_18_R1.block.CraftBlock.getState(CraftBlock.java:329) ~[paper-1.18.1.jar:git-Paper-132]
at org.bukkit.craftbukkit.v1_18_R1.block.CraftBlock.getState(CraftBlock.java:321) ~[paper-1.18.1.jar:git-Paper-132]
at net.coreprotect.CoreProtectAPI.logRemoval(CoreProtectAPI.java:297) ~[CoreProtect-20.3.jar:?]
at com.syntaxphoenix.spigot.smoothtimber.compatibility.coreprotect.CoreCompat_v1_13_x.logRemoval(CoreCompat_v1_13_x.java:19) ~[smoothtimber-legacy-1.18.3.jar:?]
at com.syntaxphoenix.spigot.smoothtimber.compatibility.coreprotect.CoreProtectGrowListener.lambda$onGrow$0(CoreProtectGrowListener.java:29) ~[smoothtimber-legacy-1.18.3.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-132]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-132]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-132]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**To Reproduce**

Unsure, no one was using it at the moment.

**Expected behavior**

Fix origin of error message

**Media**

**Server:**
Paper 1.18.1-132
1.18.3
JDK17

**Additional context**

**Comment by Lauriichan** [comment]
The plugin doesn't do anything if nobody is using the plugin.
SmoothTimber does not just chop trees.
If you got compatibilities installed, CoreProtect in your case it listenes to other events as well.
In this case the StructureGrowthEvent

**Comment by Lauriichan** [comment]
Normally the StructureGrowEvent is called synchronously to the main thread but it seems like in terms of Paper this isn't the case.
Therefore yes this is a bug but only Paper related

**Comment by NathanAdhitya** [comment]
Hello, just chiming in. I experienced the same bug in my server. I have CoreProtect 21.2 and SmoothTimber 1.22.4.
```
[17:23:24] [Craft Scheduler Thread - 19 - SmoothTimber/WARN]: [SmoothTimber] Plugin SmoothTimber v1.22.4 generated an exception while executing task 57331
java.lang.IllegalStateException: Tile is null, asynchronous access? CraftBlock{pos=BlockPosition{x=0, y=68, z=-709},type=BEE_NEST,data=Block{minecraft:bee_nest}[facing=south,honey_level=0],fluid=net.minecraft.world.level.material.FluidTypeEmpty@382bb7d5}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:590) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:92) ~[paper-1.19.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:78) ~[paper-1.19.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:278) ~[paper-1.19.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:236) ~[paper-1.19.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:221) ~[paper-1.19.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.getState(CraftBlock.java:329) ~[paper-1.19.2.jar:git-Paper-301]
	at net.coreprotect.CoreProtectAPI.logRemoval(CoreProtectAPI.java:331) ~[CoreProtect-21.2.jar:?]
	at com.syntaxphoenix.spigot.smoothtimber.compatibility.coreprotect.CoreCompat_v1_13_x.logRemoval(CoreCompat_v1_13_x.java:19) ~[smoothtimber-legacy-1.22.4.jar:?]
	at com.syntaxphoenix.spigot.smoothtimber.compatibility.coreprotect.CoreProtectGrowListener.lambda$onGrow$0(CoreProtectGrowListener.java:29) ~[smoothtimber-legacy-1.22.4.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-301]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Lauriichan** [comment]
This might no longer be an issue atleast on folia - don't know if it still is on paper, someone might want to test it
