### ISSUE TITLE
[BUG]: Could not pass event AsyncPlayerChopTreeEvent to SmoothTimber v1.22.1

### ISSUE THREAD

**Issue by TeemoCell** [SourceWriters/SmoothTimber#45]
### Describe what happend

```
[17:26:14 ERROR]: Could not pass event AsyncPlayerChopTreeEvent to SmoothTimber v1.22.1
java.lang.NoClassDefFoundError: com/gmail/nossr50/datatypes/skills/PrimarySkillType
        at com.syntaxphoenix.spigot.smoothtimber.compatibility.mcmmo.McMmoChopListener.onChopEvent(McMmoChopListener.java:25) ~[smoothtimber-legacy-1.22.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor81.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-61]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at com.syntaxphoenix.spigot.smoothtimber.SmoothTimber.triggerChopEvent(SmoothTimber.java:57) ~[smoothtimber-legacy-1.22.1.jar:?]
        at com.syntaxphoenix.spigot.smoothtimber.listener.BlockBreakListener$1.run(BlockBreakListener.java:96) ~[smoothtimber-legacy-1.22.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-61]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-61]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.datatypes.skills.PrimarySkillType
        ... 14 more
```

https://paste.teemocell.dev/pemubofuwe

### Reproduction steps

1. Install Plugin
2. Chop trees ingame

### Expected behavior

No Error!!

### Media

![chrome_uzyuhVRiNx](https://user-images.githubusercontent.com/11705513/179408894-e9294349-b323-4ccf-8b27-74ac4a90afc2.png)

### Java Version

Java 17

### Server Software

Paper

### Minecraft Version

1.19

### Plugin Version

1.22.1

**Comment by Lauriichan** [comment]
This is related to the MCMMO compatibility, seems like they changed something.
Which version of MCMMO is installed on your server?

**Comment by Lauriichan** [comment]
Also as a temporary solution you could disable the MCMMO support in the addons.yml

**Comment by TeemoCell** [comment]
Oh i think that was my fault. I was using the Pre-Relase from `Dec 25, 2018` -_-
