### ISSUE TITLE
[BUG] Tree broke, then came back, error in console

### ISSUE THREAD

**Issue by wiilover22** [SourceWriters/SmoothTimber#6]
**Describe the bug**
As title says - tree broke in-game, re-appeared, error in log

**To Reproduce**
No sure, happens randomly. Not often.

**Expected behavior**
Proper behavior in game, no error in log.

**Media**
`[22:09:13] [Server thread/WARN]: [SmoothTimber] Task #16652204 for SmoothTimber v1.15.0 generated an exception
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "<parameter1>" is null
	at java.util.EnumMap.typeCheck(Unknown Source) ~[?:?]
	at java.util.EnumMap.put(Unknown Source) ~[?:?]
	at com.syntaxphoenix.spigot.smoothtimber.event.AsyncPlayerTreeFallEvent.add(AsyncPlayerTreeFallEvent.java:40) ~[?:?]
	at com.syntaxphoenix.spigot.smoothtimber.listener.BlockBreakListener$1$1.run(BlockBreakListener.java:96) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-"81a537c1f"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-"81a537c1f"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1426) ~[patched_1.16.5.jar:git-Paper-"81a537c1f"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-"81a537c1f"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1341) ~[patched_1.16.5.jar:git-Paper-"81a537c1f"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129) ~[patched_1.16.5.jar:git-Paper-"81a537c1f"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-"81a537c1f"]
	at java.lang.Thread.run(Unknown Source) [?:?]`

**Server:**

 - Software: Paper 1.16.5
 - Server Version: 1.16.5
 - Plugin Version: v1.15.0

**Comment by Lauriichan** [comment]
Yeah we already know about that one but we don't know why it happens, did u try the latest version already?
Maybe that fixes it

**Comment by Lauriichan** [comment]
Should be fixed in 6913178fbb7f331e0eeed38bc592395f280bb78e
