### ISSUE TITLE
[BUG]: Breaking trees with fist

### ISSUE THREAD

**Issue by Tranzitron** [SourceWriters/SmoothTimber#67]
### Describe what happend

I added the air material to be able to break the trees with my hand, and everytime i break a tree, the logs replaces itself (event is cancelled). 

```
materials:
  - AIR
  - WOODEN_AXE
  - STONE_AXE
  - IRON_AXE
  - GOLDEN_AXE
  - DIAMOND_AXE
  - NETHERITE_AXE
```
Error stack:
```
[WARN]: [SmoothTimber] Task #108 for SmoothTimber v1.24.4 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.isUnbreakable()" because "meta" is null
        at com.syntaxphoenix.spigot.smoothtimber.version.changer.v1_20xChanger.removeDurabilityFromItem(v1_20xChanger.java:51) ~[smoothtimber-legacy-1.24.4.jar:?]
        at com.syntaxphoenix.spigot.smoothtimber.listener.BlockBreakListener$1.run(BlockBreakListener.java:106) ~[smoothtimber-legacy-1.24.4.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-42]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-42]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-42]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

### Reproduction steps

1. Add the AIR material to the materials list
2. Save the config and restart the server
3. Break a tree with your fist

### Expected behavior

The tree should be broken as normal

### Java Version

Java 18

### Server Software

Paper

### Minecraft Version

1.20.1

### Plugin Version

1.24.4

**Comment by Tranzitron** [comment]
https://github.com/SourceWriters/SmoothTimber/pull/68
