### ISSUE TITLE
[BUG]: Limit issue + precalculation

### ISSUE THREAD

**Issue by Glionox** [SourceWriters/SmoothTimber#73]
### Describe what happend

If create a huge tree with tens of thousands of blocks and hit it once, the plugin will long count the blocks and knock out the number of blocks that corresponds to the strength, or all, if the axe is unbreakable (the limit does not work, although set to 1000). The number of entity after unbreakable axe collapses TPS in 0 because of tens of thousands of entities. If make several hits in different places can overload the CPU of server. The same problem applies to dense forests with custom generation, where the whole forest is a solid tree for the plugin.

### Reproduction steps

1. Create large tree like this:
![imagse](https://github.com/SourceWriters/SmoothTimber/assets/58746661/5e5a7630-66b5-4e30-b462-ef8f545f98cc)
2. Try to chop down.
3. After N minutes tree fall.

### Expected behavior

The tree falls in a much shorter wait time depending on the block limit without precalculating the entire tree.

### Media

An example of a dense forest.
![2023-08-20_12 05 28](https://github.com/SourceWriters/SmoothTimber/assets/58746661/caf363f9-011e-40c4-929d-9f78ca1ad529)

Result. Only the upper part of the trees was cut down.
![2023-08-20_12 05 46](https://github.com/SourceWriters/SmoothTimber/assets/58746661/d3403a9d-4262-4bb7-aafd-0bd611328aa7)

OutOfMemoryError:
`[21:57:56] [Craft Scheduler Thread - 2728 - SmoothTimber/WARN]: [SmoothTimber] Plugin SmoothTimber v1.24.6 generated an exception while executing task 20333363
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.lang.Thread.start0(Native Method) ~[?:?]
	at java.lang.Thread.start(Thread.java:802) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1364) ~[?:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) ~[?:?]
	at com.syntaxphoenix.spigot.smoothtimber.compatibility.coreprotect.CoreProtectResolver.resolve(CoreProtectResolver.java:59) ~[smoothtimber-legacy-1.24.6.jar:?]
	at com.syntaxphoenix.spigot.smoothtimber.utilities.locate.Locator.locateWood(Locator.java:92) ~[smoothtimber-legacy-1.24.6.jar:?]
	at com.syntaxphoenix.spigot.smoothtimber.listener.BlockBreakListener.lambda$onBlockBreak$2(BlockBreakListener.java:89) ~[smoothtimber-legacy-1.24.6.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### Java Version

Java 17

### Server Software

Purpur

### Minecraft Version

1.20.1

### Plugin Version

1.24.6

**Comment by Lauriichan** [comment]
The limit in SmoothTimber works based on permissions.
Operators have a bypass permission that allows them to ignore the block limit.

**Comment by Lauriichan** [comment]
The limit shown in the config is not a hard limit but a default limit value.
You can define different limits for different ranks on your server if that is something you want.
Either way you should deop yourself if you want to use the limit function of SmoothTimber and instead of being op use a permission plugin that allows you to give you every permission except the "smoothtimber.limit.*" permission or just remove that permission from yourself using a permissions plugin

**Comment by Lauriichan** [comment]
Also as a side note if there is a limit active then SmoothTimber stops in the middle of the wood detection process which makes this not a bug but instead a help issue.

**Comment by Glionox** [comment]
Thank you. That was my mistake. smoothtimber.* was in permissions even for regular players. I set the limit through the permissions and everything is fine now.
