### ISSUE TITLE
[COMPAT]: Add Compability to SaberFaction

### ISSUE THREAD

**Issue by SkulZOnTheYT** [SourceWriters/SmoothTimber#78]
### Server Software

Paper

### Minecraft Version

1.20.2

### Plugin Name

SaberFaction

### Plugin Version

all

### Why should we add compatibility for this plugin with that version?

please add compatibility to saber faction plugin, not just to factionUUID.

### Additional Information

[08:20:46 INFO]: SmoothTimber || com.syntaxphoenix.spigot.smoothtimber.compatibility.IncompatiblePluginException: Found a Factions plugin not presently supported by SmoothTimber
        at com.syntaxphoenix.spigot.smoothtimber.compatibility.factionsuuid.FactionsUUID.onEnable(FactionsUUID.java:26)
        at com.syntaxphoenix.spigot.smoothtimber.compatibility.CompatibilityHandler$CompatAddon.start(CompatibilityHandler.java:137)
        at com.syntaxphoenix.spigot.smoothtimber.compatibility.CompatibilityHandler.handleSettingsUpdate(CompatibilityHandler.java:90)
        at com.syntaxphoenix.spigot.smoothtimber.utilities.PluginUtils.checkPlugins(PluginUtils.java:78)
        at com.syntaxphoenix.spigot.smoothtimber.utilities.PluginUtils.<init>(PluginUtils.java:61)
        at com.syntaxphoenix.spigot.smoothtimber.utilities.PluginUtils.setUp(PluginUtils.java:47)
        at com.syntaxphoenix.spigot.smoothtimber.SmoothTimber.onEnable(SmoothTimber.java:36)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190)
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646)
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557)
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627)
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
        at java.lang.Thread.run(Thread.java:840)

**Comment by Lauriichan** [comment]
Please specify the plugin version that you were using at that point in time and not "all" - we can't easily support every version that exists of a given plugin and will most likely only prioritize the latest one.

**Comment by Lauriichan** [comment]
Also in my opinion it is just stupid of all those faction plugin developers to only call their plugin "Factions" - this makes it harder for other plugins to keep track of it.

**Comment by SkulZOnTheYT** [comment]
> Please specify the plugin version that you were using at that point in time and not "all" - we can't easily support every version that exists of a given plugin and will most likely only prioritize the latest one.

I am using saber faction plugin version 4.1.3-Stable

**Comment by rackgaming** [comment]
just updated to 4.1.4-stable for saber factions

**Comment by rackgaming** [comment]
paper 1.20.4
