### ISSUE TITLE
[BUG]: Error on Folia 1.20.4

### ISSUE THREAD

**Issue by meridianrealms** [SourceWriters/SmoothTimber#81]
### Describe what happend

I get the error below when loading SmoothTimber on any version of Folia I have tried. I'm currently using the build of Folia I compiled today. 

### Reproduction steps

Install plugin on Folia and start the server.

### Expected behavior

No errors. 

### Media

`[22:26:08 INFO]: [SmoothTimber] Enabling SmoothTimber v1.25.0
[22:26:08 INFO]: SmoothTimber || You're currently using the supported Minecraft Version 1.20.4 (Core v1_20x)
[22:26:08 INFO]: SmoothTimber || Trying to enable compatibility addon 'CoreProtect' for plugin 'CoreProtect'...
[22:26:08 INFO]: SmoothTimber || Successfully enabled compatbility addon 'CoreProtect' for plugin 'CoreProtect'...
[22:26:08 ERROR]: Error occurred while enabling SmoothTimber v1.25.0 (Is it up to date?)
java.lang.IllegalArgumentException: Period may not be <= 0
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler.runAtFixedRate(FoliaAsyncScheduler.java:113) ~[folia-1.20.4.jar:?]       
        at com.syntaxphoenix.spigot.smoothtimber.platform.FoliaPlatform.asyncTaskTimer(FoliaPlatform.java:82) ~[smoothtimber-legacy-1.25.0.jar:?]  
        at com.syntaxphoenix.spigot.smoothtimber.toggle.ToggleTimer.<init>(ToggleTimer.java:11) ~[smoothtimber-legacy-1.25.0.jar:?]
        at com.syntaxphoenix.spigot.smoothtimber.toggle.ToggleStorage.<init>(ToggleStorage.java:22) ~[smoothtimber-legacy-1.25.0.jar:?]
        at com.syntaxphoenix.spigot.smoothtimber.SmoothTimber.onEnable(SmoothTimber.java:40) ~[smoothtimber-legacy-1.25.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:645) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:556) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:713) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:458) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### Java Version

Java 17

### Server Software

Folia

### Minecraft Version

1.20.4

### Plugin Version

1.25.0

**Comment by Lauriichan** [comment]
Seems like our scheduler is probably setting some values wrong on the tick timers, well yeah that probably needs fixing
