### ISSUE TITLE
[BUG]:  Could not pass event AsyncPlayerChopTreeEvent to SmoothTimber 

### ISSUE THREAD

**Issue by legendofgow** [SourceWriters/SmoothTimber#86]
### Describe what happend

Error with lands 

`[15:15:18 ERROR]: Could not pass event AsyncPlayerChopTreeEvent to SmoothTimber v1.25.0
java.lang.NoClassDefFoundError: me/angeschossen/lands/api/role/enums/RoleSetting
        at com.syntaxphoenix.spigot.smoothtimber.compatibility.lands.LandsChopListener.onChopEvent(LandsChopListener.java:30) ~[smoothtimber-legacy-1.25.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor867.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2174]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2174]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2174]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at com.syntaxphoenix.spigot.smoothtimber.SmoothTimber.triggerChopEvent(SmoothTimber.java:60) ~[smoothtimber-legacy-1.25.0.jar:?]
        at com.syntaxphoenix.spigot.smoothtimber.listener.BlockBreakListener.lambda$onBlockBreak$2(BlockBreakListener.java:91) ~[smoothtimber-legacy-1.25.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2174]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2174]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.angeschossen.lands.api.role.enums.RoleSetting
        ... 16 more`

### Reproduction steps

When you cut down tree on you land in lands plugin

### Expected behavior

No error at all

### Java Version

Java 18

### Server Software

Purpur

### Minecraft Version

1.20.4

### Plugin Version

1.25.0

**Comment by Lauriichan** [comment]
Please update to 1.27.0

**Comment by legendofgow** [comment]
On 1.27.0 its still showing that error

`[12:07:13 ERROR]: Could not pass event AsyncPlayerChopTreeEvent to SmoothTimber v1.27.0
java.lang.NoClassDefFoundError: me/angeschossen/lands/api/role/enums/RoleSetting
        at com.syntaxphoenix.spigot.smoothtimber.compatibility.lands.LandsChopListener.onChopEvent(LandsChopListener.java:30) ~[smoothtimber-legacy-1.27.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1347.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2174]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2174]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2174]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at com.syntaxphoenix.spigot.smoothtimber.SmoothTimber.triggerChopEvent(SmoothTimber.java:60) ~[smoothtimber-legacy-1.27.0.jar:?]
        at com.syntaxphoenix.spigot.smoothtimber.listener.BlockBreakListener.lambda$onBlockBreak$2(BlockBreakListener.java:91) ~[smoothtimber-legacy-1.27.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2174]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2174]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.angeschossen.lands.api.role.enums.RoleSetting
        ... 16 more`

**Comment by Lauriichan** [comment]
Please open a compatibility request instead

**Comment by Lauriichan** [comment]
Reason why: This is related to lands and I need to know what you are using and it's faster if u just create a new issue with the information required
