### ISSUE TITLE
[BUG]: Error

### ISSUE THREAD

**Issue by Strahilchu** [SourceWriters/SmoothTimber#88]
### Describe what happend

[00:10:44 WARN]: [SmoothTimber] Plugin SmoothTimber v1.27.0 generated an exception while executing task 2513166
java.lang.IllegalStateException: Tile is null, asynchronous access? CraftBlock{pos=BlockPosition{x=32536, y=67, z=29256},type=BEE_NEST,data=Block{minecraft:bee_nest}[facing=south,honey_level=0],fluid=net.minecraft.world.level.material.FluidTypeEmpty@8b48a15}
        at com.google.common.base.Preconditions.checkState(Preconditions.java:601) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:98) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:84) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlockStates.getBlockState(CraftBlockStates.java:297) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlockStates.getBlockState(CraftBlockStates.java:249) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlockStates.getBlockState(CraftBlockStates.java:234) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlock.getState(CraftBlock.java:334) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.coreprotect.CoreProtectAPI.logRemoval(CoreProtectAPI.java:357) ~[CoreProtect-22.4.jar:?]
        at com.syntaxphoenix.spigot.smoothtimber.compatibility.coreprotect.CoreCompat_v1_13_x.logRemoval(CoreCompat_v1_13_x.java:22) ~[smoothtimber-legacy-1.27.0.jar:?]
        at com.syntaxphoenix.spigot.smoothtimber.compatibility.coreprotect.CoreProtectGrowListener.lambda$onGrow$0(CoreProtectGrowListener.java:29) ~[smoothtimber-legacy-1.27.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Reproduction steps

Unknown

### Expected behavior

No error

### Java Version

Java 18

### Server Software

Purpur

### Minecraft Version

1.20.4

### Plugin Version

1.27.0

**Comment by Lauriichan** [comment]
I'm not sure if this is still the case?
