### ISSUE TITLE
[BUG]: Tree from terraform generator

### ISSUE THREAD

**Issue by TymekSL** [SourceWriters/SmoothTimber#95]
### Describe what happend

Cut big tree from terraform generator plugin, has been brake i got planks but got errors too

### Reproduction steps

Trying cut big treew using terraform generator

### Expected behavior

Fix it 

### Media

[19:45:44 WARN]: [SmoothTimber] Task #6052 for SmoothTimber v1.27.0 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.isUnbreakable()" because "meta" is null
        at smoothtimber-legacy-1.27.0.jar/com.syntaxphoenix.spigot.smoothtimber.version.changer.v1_20xChanger.removeDurabilityFromItem(v1_20xChanger.java:60) ~[smoothtimber-legacy-1.27.0.jar:?]
        at smoothtimber-legacy-1.27.0.jar/com.syntaxphoenix.spigot.smoothtimber.listener.BlockBreakListener$1.run(BlockBreakListener.java:107) ~[smoothtimber-legacy-1.27.0.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:45:45 INFO]: BloodyMonkey383 issued server command: /tps

### Java Version

Java 21

### Server Software

paper spigot

### Minecraft Version

1.21.1

### Plugin Version

TerraformGenerator-16.3.0.jar

**Comment by Lauriichan** [comment]
I will check this soon
