### ISSUE TITLE
[BUG]: Could not pass event AsyncPlayerChopTreeEvent to SmoothTimber v1.27.2

### ISSUE THREAD

**Issue by xUS4R** [SourceWriters/SmoothTimber#98]
### Describe what happend

So everytime a player mines a tree instantly this error gets sent to the console and its something with the WorldGuard addon, and if y'all could fix it, it would be great.

### Reproduction steps

Go to a tree, mine it and if u have world guard installed and the addon section on true it just gets sended into the console.

### Expected behavior

I expected to not have this error pop in console.

### Media

 [18:36:56 ERROR]: Could not pass event AsyncPlayerChopTreeEvent to SmoothTimber v1.27.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1620]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.syntaxphoenix.spigot.smoothtimber.SmoothTimber.triggerChopEvent(SmoothTimber.java:60) ~[?:?]
        at com.syntaxphoenix.spigot.smoothtimber.listener.BlockBreakListener.lambda$onBlockBreak$2(BlockBreakListener.java:91) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "com.syntaxphoenix.spigot.smoothtimber.shaded.syntaxapi.reflection.AbstractReflect.run(Object, String, Object[])" is null
        at com.syntaxphoenix.spigot.smoothtimber.compatibility.worldguard.WorldGuardChopListener_v6_x.onChopEvent(WorldGuardChopListener_v6_x.java:29) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor499.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 11 more

### Java Version

Java 21

### Server Software

PaperMC

### Minecraft Version

1.12.2

### Plugin Version

1.27.2

**Comment by FadingArrow560** [comment]
I am experiencing the same issue. Doesn't seems to be actually causing any problems or conflicts.. but its concerning to see in the console constantly.

**Comment by PeppoDevStudio** [comment]
i have this issue

**Comment by Lauriichan** [comment]
Is this still the case?
